export const mockProducts = [
  {
    id: 1,
    name: 'Ceramic Vase',
    artist: 'María González',
    price: 45.00,
    description: 'Jarrón de cerámica hecho a mano con técnicas ancestrales. Cada pieza es única y refleja la personalidad del artista.',
    process: 'Elaborado mediante torno alfarero, cocido a 1200°C y esmaltado con óxidos naturales.',
    category: 'ceramics',
    image: null,
    inStock: true,
  },
  {
    id: 2,
    name: 'Minimal Table Lamp',
    artist: 'Studio Alem',
    price: 120.00,
    description: 'Lámpara de mesa con diseño minimalista, perfecta para espacios contemporáneos.',
    process: 'Estructura de acero inoxidable con acabado mate y pantalla de lino natural.',
    category: 'lighting',
    image: null,
    inStock: true,
  },
  {
    id: 3,
    name: 'Wool Cushion',
    artist: 'Textile Lab',
    price: 35.00,
    description: 'Cojín tejido a mano con lana merino de alta calidad.',
    process: 'Tejido artesanal con telares tradicionales, teñido con tintes naturales.',
    category: 'textiles',
    image: null,
    inStock: true,
  },
  {
    id: 4,
    name: 'Concrete Planter',
    artist: 'Carlos Ruiz',
    price: 28.00,
    description: 'Maceta de hormigón con diseño geométrico minimalista.',
    process: 'Moldeado en hormigón arquitectónico con sellado hidrofóbico interior.',
    category: 'objects',
    image: null,
    inStock: true,
  },
  {
    id: 5,
    name: 'Glass Carafe',
    artist: 'Vidrio Studio',
    price: 38.00,
    description: 'Jarra de vidrio soplado con formas orgánicas.',
    process: 'Vidrio soplado artesanalmente a 1000°C, cada pieza es única.',
    category: 'glass',
    image: null,
    inStock: false,
  },
  {
    id: 6,
    name: 'Wooden Tray',
    artist: 'Madera Viva',
    price: 55.00,
    description: 'Bandeja de madera maciza con acabado natural.',
    process: 'Tallada en madera de nogal, tratada con aceites naturales.',
    category: 'wood',
    image: null,
    inStock: true,
  },
]

export const mockProjects = [
  {
    id: 1,
    title: 'Pasaje 94',
    location: 'Valencia',
    year: '2025',
    category: 'Comercial',
    description: 'Somos dos arquitectas que piensan como una y hacen por mil. Diseñamos los metros cuadrados a nuestra medida. El espacio está ubicado en el corazón de Valencia, en la calle Trinitarios número 13. El local estuvo cerrado durante 25 años, utilizado como trastero o garaje, deshabitado y olvidado por el resto de la ciudad. La reforma fue un proceso de recuperación: conservar lo que existía y dejar el espacio lo más diáfano posible para que cada programa tenga su lugar. Además de ser nuestro despacho de arquitectura, nuestra sede de estudio y trabajo, es un lugar abierto a la comunidad. La entrada es a través de la cafetería de Pasaje 94, nuestro escaparate como diseñadoras y puerta de acceso a este universo creativo. Un café pensado para ser parte de tu rutina diaria, como ese momento de respiro y de pausa. El área de exhibición varía a lo largo del año, según los diseñadores y proyectos presentes en cada etapa. Nos mueve el detrás de escena, el proceso creativo que impulsa nuevas ideas. Por eso creamos un espacio que acompaña la expansión del diseño y del pensamiento creativo. El patio es un espacio verde, fresco todo el año y en constante crecimiento. De uso privado, está reservado para quienes forman parte del área de trabajo, ofreciendo un entorno saludable para crear y colaborar. Un espacio donde el diseño reflexivo se crea y se comparte en sintonía con el ritmo de la vida cotidiana y la experiencia.',
    image: null,
  },
  {
    id: 2,
    title: 'Mesa Causa 01',
    location: '',
    year: '',
    category: '',
    description: 'Una mesa que surge del espacio que habita. La estructura existente moldea su forma, generando una serie de cortes que responden a su función. Pequeñas intervenciones que no solo la adaptan al lugar, sino que invitan a nuevas formas de habitarla y de relacionarnos con el entorno.',
    image: null,
  },
  {
    id: 3,
    title: 'Mesa Causa 02',
    location: '',
    year: '',
    category: '',
    description: 'Proponemos esta mesa a partir de un encuentro casual, como es la relación de distancia que nos unen, una distancia en ocasiones no separa, une. Nos hace conscientes del otro, de su ausencia, de su valor. Nos invita a encontrar otras formas de estar cerca.',
    image: null,
  },
  {
    id: 4,
    title: 'Mesa Causa 03',
    location: '',
    year: '',
    category: '',
    description: 'Una mesa que se funde con el paisaje. Es la causa del encuentro, un gesto que invita a compartir, observar y ser parte del entorno. Un círculo que nos une, como cuando nos sentamos a un picnic en el campo. La mesa se funde con el paisaje, se diluye como objeto y pasa a ser parte del lugar.',
    image: null,
  },
  {
    id: 5,
    title: 'Osnova Gallery',
    location: 'Valencia',
    year: '2025',
    category: 'Galería de Arte',
    description: 'New project - coming soon',
    image: null,
  },
]

export const mockExhibitions = [
  {
    id: 2,
    title: 'Luz y Sombra',
    artist: 'Studio de Iluminación',
    startDate: '2024-09-15',
    endDate: '2024-10-30',
    description: 'Instalación de luminarias diseñadas específicamente para el espacio.',
    current: false,
    image: null,
  },
]