export const mockProducts = [
  {
    id: 1,
    name: 'Ceramic Vase',
    artist: 'María González',
    price: 45.00,
    description: 'Jarrón de cerámica hecho a mano con técnicas ancestrales. Cada pieza es única y refleja la personalidad del artista.',
    process: 'Elaborado mediante torno alfarero, cocido a 1200°C y esmaltado con óxidos naturales.',
    category: 'ceramics',
    image: null,
    inStock: true,
  },
  {
    id: 2,
    name: 'Minimal Table Lamp',
    artist: 'Studio Alem',
    price: 120.00,
    description: 'Lámpara de mesa con diseño minimalista, perfecta para espacios contemporáneos.',
    process: 'Estructura de acero inoxidable con acabado mate y pantalla de lino natural.',
    category: 'lighting',
    image: null,
    inStock: true,
  },
  {
    id: 3,
    name: 'Wool Cushion',
    artist: 'Textile Lab',
    price: 35.00,
    description: 'Cojín tejido a mano con lana merino de alta calidad.',
    process: 'Tejido artesanal con telares tradicionales, teñido con tintes naturales.',
    category: 'textiles',
    image: null,
    inStock: true,
  },
  {
    id: 4,
    name: 'Concrete Planter',
    artist: 'Carlos Ruiz',
    price: 28.00,
    description: 'Maceta de hormigón con diseño geométrico minimalista.',
    process: 'Moldeado en hormigón arquitectónico con sellado hidrofóbico interior.',
    category: 'objects',
    image: null,
    inStock: true,
  },
  {
    id: 5,
    name: 'Glass Carafe',
    artist: 'Vidrio Studio',
    price: 38.00,
    description: 'Jarra de vidrio soplado con formas orgánicas.',
    process: 'Vidrio soplado artesanalmente a 1000°C, cada pieza es única.',
    category: 'glass',
    image: null,
    inStock: false,
  },
  {
    id: 6,
    name: 'Wooden Tray',
    artist: 'Madera Viva',
    price: 55.00,
    description: 'Bandeja de madera maciza con acabado natural.',
    process: 'Tallada en madera de nogal, tratada con aceites naturales.',
    category: 'wood',
    image: null,
    inStock: true,
  },
]

export const mockProjects = [
  {
    id: 1,
    title: 'Casa Mediterránea',
    location: 'Valencia, España',
    year: '2024',
    category: 'Residential',
    description: 'Proyecto residencial que fusiona arquitectura contemporánea con elementos tradicionales mediterráneos.',
    image: null,
  },
  {
    id: 2,
    title: 'Espacio Pasaje 94',
    location: 'Valencia, España',
    year: '2024',
    category: 'Commercial',
    description: 'Diseño y construcción de nuestro propio espacio: estudio, café y galería.',
    image: null,
  },
  {
    id: 3,
    title: 'Vivienda Minimalista',
    location: 'Madrid, España',
    year: '2023',
    category: 'Residential',
    description: 'Reforma integral con enfoque minimalista y materiales naturales.',
    image: null,
  },
]

export const mockExhibitions = [
  {
    id: 2,
    title: 'Luz y Sombra',
    artist: 'Studio de Iluminación',
    startDate: '2024-09-15',
    endDate: '2024-10-30',
    description: 'Instalación de luminarias diseñadas específicamente para el espacio.',
    current: false,
    image: null,
  },
]